Repository cher-ange/TP05GRUPO201, pull requests merged in 2024-07, with the labels that each got.

#9 Feature/apply-relationships-to-entities-GutierrezAngelGonzalo
  src/main/java/ar/edu/unju/fi/tp05grupo201/controller/HomeController.java
  src/main/java/ar/edu/unju/fi/tp05grupo201/dto/StudentDto.java
Labels: enhancement

#15 Implementado uso de DTO a la relacion Docente-Materia
  src/main/java/ar/edu/unju/fi/tp05grupo201/controller/SubjectController.java
  src/main/java/ar/edu/unju/fi/tp05grupo201/controller/TeacherController.java
  src/main/java/ar/edu/unju/fi/tp05grupo201/mapper/CareerMapper.java
  src/main/java/ar/edu/unju/fi/tp05grupo201/mapper/StudentMapper.java
  src/main/java/ar/edu/unju/fi/tp05grupo201/mapper/SubjectMapper.java
  src/main/java/ar/edu/unju/fi/tp05grupo201/service/ISubjectService.java
  src/main/java/ar/edu/unju/fi/tp05grupo201/service/ITeacherService.java
  src/main/java/ar/edu/unju/fi/tp05grupo201/service/imp/StudentServiceImp.java
  src/main/java/ar/edu/unju/fi/tp05grupo201/service/imp/SubjectServiceImp.java
  src/main/java/ar/edu/unju/fi/tp05grupo201/service/imp/TeacherServiceImp.java
  src/main/resources/templates/subject/subjects.html
Labels: documentation, enhancement

#16 Implementacion de Dtos a Carrera, tambien se implementan validaciones…
  src/main/java/ar/edu/unju/fi/tp05grupo201/service/ICareerService.java
  src/main/java/ar/edu/unju/fi/tp05grupo201/service/imp/CareerServiceImp.java
  src/main/resources/application.properties
Labels: bug

#17 Arreglar metodo modificar de Carrera-Materia
  src/main/java/ar/edu/unju/fi/tp05grupo201/controller/CareerController.java
  src/main/java/ar/edu/unju/fi/tp05grupo201/controller/StudentController.java
  src/main/java/ar/edu/unju/fi/tp05grupo201/model/Career.java
  src/main/java/ar/edu/unju/fi/tp05grupo201/model/Student.java
  src/main/java/ar/edu/unju/fi/tp05grupo201/model/Subject.java
  src/main/java/ar/edu/unju/fi/tp05grupo201/model/Teacher.java
  src/main/java/ar/edu/unju/fi/tp05grupo201/service/ICareerService.java
  src/main/java/ar/edu/unju/fi/tp05grupo201/service/IStudentService.java
  src/main/java/ar/edu/unju/fi/tp05grupo201/service/imp/CareerServiceImp.java
  src/main/java/ar/edu/unju/fi/tp05grupo201/service/imp/StudentServiceImp.java
  src/main/java/ar/edu/unju/fi/tp05grupo201/service/imp/SubjectServiceImp.java
  src/main/resources/application.properties
  src/main/resources/templates/career/add-subject-to-career.html
  src/main/resources/templates/student/add-subject-to-student.html
Labels: bug, help wanted

#18 Arreglado metodo modificar Carrera sin perder las relaciones
  src/main/java/ar/edu/unju/fi/tp05grupo201/service/imp/CareerServiceImp.java
  src/main/resources/application.properties
Labels: enhancement
